resume_dir: ../Data
webdriver_dir: C://Users//P0142221//Downloads//chromedriver_win32//chromedriver.exe
pdf_dir: ..Data
uname: praveen159sk@gmail.com
pwd: Websites@27

skills:
    - java
    - c
    - c++
    - c#
    - .net
    - matlab
    - r
    - python
    - vhdl
    - php
    - javascript
    - machine learning algorithms 
    - tableau
    - hadoop
    - spark
    - neural network
    - deep learning
    - artificial neural networks
    - machine learning 
    - aws
    - azure ml
      
url_encoder: https%3A%2F%2Fsampappl.azurewebsites.net%2F
client_id: 86wzh8xzhz8zp5
client_secret: PI7IvVqMopyt3qCV
redirect_url: 'https://sampappl.azurewebsites.net/'
access_token: AQXPXYDO0IbBhSAl76aUwCMe1oslniKEvvhOSvcm1SosY0EuFFCh80pAz3I1wdHXTq5JfOH9hUW8iuC5deGzOfs8D3MY2IZR_s8c0w8Vt2ICPtoAH_ilrMHxrDfZxfFYUkwzZHCJH-YD4qDbn-msx8XAtScfWQsxQCYtcop0kYlJ2Ne--85Zm_agrTdd5_ZZ87nddpGDbjbyLk1nxaAcI42hchcm9r6GLmWz_U2ZrxgjX-DJH91o8zxrOfXiRcF2jh1EpXQSI7jvW7o4rVH5_Xw1rPRmFL2ZhLmtRCXdEA02PEA0ZCr5XZ1vpMLI8SEToRIOF-2bxD8p3MPk6TAm9xk4ZIANzg


